### ISSUE TITLE
Polymer 3

### ISSUE THREAD

**Issue by rwestlund** [pkaske/chart-elements#76]
This needs to be run through the modulizer and pushed to npm.

**Comment by Hunsin** [comment]
Will there be a `lit-element` version of chartjs also?

**Comment by pkaske** [comment]
I'm not uncertain what the Polymer team plans to favor in the future. It seems to me that they maybe go all in on lit-element and ditch the polymer binding syntax in the long run. I would like know that in order to make a future proof version of the element.

Does anybody already have a definitiv statement on that subject? @robdodson, you maybe?

**Comment by rwestlund** [comment]
They said so on the Polymer blog:
https://www.polymer-project.org/blog/2018-05-02-roadmap-update.html
Also see the FAQ linked at the bottom.

They're not only dropping the Polymer 2 syntax, they're going to deprecate all the `iron-*`, `paper-*`, etc elements in favor of new `lit-element` implementations.  Their new implementations are beautifully minimal.

**Comment by pkaske** [comment]
I have a prototype based on lit-element ready. It's on the [polymer-3.0-lit-element](https://github.com/robdodson/chart-elements/tree/polymer-3.0-lit-element) branch.
I would really appreciate if you guys could give it a try and give me feedback.

It's a near re-write and comes without iron-resize-behavior, so I guess there will probably unwanted side effects.

**Comment by RoXuS** [comment]
Hi @pkaske,

We did some tests on polymer 3, Chart.js doesn't offer an esm import so we have used a basic script import like this : https://github.com/RoXuS/chart-elements/blob/polymer3/chart-js-import.js .

We have tried on the chart-line element like this: https://github.com/RoXuS/chart-elements/blob/polymer3/chart-line.js and is work good with a simple import: `import '@pkaske/chart-elements/chart-line';`.

Do you think that is the good way to go ?

**Comment by RoXuS** [comment]
Oh yeah, now I understand you polymer-3.0-lit-element branch !

You do not think it would be better to load chart.js in the component while waiting for the esm import from the chart.js team ?

**Comment by pkaske** [comment]
Yeah I thinks it's better to not load chart.js in the component. Reasons for that are
1. people my want or need to use a different version of chart.js
2. maybe chart.js is already loaded in the project when the chart-elements are introduced
3. probably better for people in regards to there bundling strategy (don't know about that, I'm new to that because till recently polymer build did everything for me)
4. i don't have to track chart.js to timely remove the import again when chart.js gets an esm version

If you feel my views are wrong or I overlook other arguments that speak for import inside the component, tell me. Definitely interested in your opinion.

**Comment by RoXuS** [comment]
Hum ok ok I understand.

It's just a shame not to be able to do: `import '@pkaske/chart-elements/chart-line';` without import `chart.js`.

We use chart-line in a component (without any html file) so we have to dynamically load `chart.js` like here  https://github.com/RoXuS/chart-elements/blob/polymer3/chart-js-import.js.
Then dynamically load `chart-line` with the same way, because if we import `chart-line` directly we will have a `Chart is not defined (context-mixin.js:40)...`.

So the component isn't usable in a component without a lot of stuff.

**Comment by pkaske** [comment]
That sucks, I understand you. As soon as there is an official esm version, I'll reconsider this.

In the meantime: There were folks you converted chart.js themselfs to esm format using rollup. Maybe that helps?
https://github.com/chartjs/Chart.js/issues/5179#issuecomment-417889559

**Comment by RoXuS** [comment]
Thx for your response, we will test this solution.

And yeah, when official esm version will be available it would be great to have this in the repo !

**Comment by emersonbottero** [comment]
@pkaske @RoXuS 
Is it a bad practice? I like it because you still keep everything in one file without the 'is not loaded' problem.

```
  ready()
  {
    //load the cdn library
    const ioscript = document.createElement('script');
    ioscript.src = 'https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.1.1/socket.io.js';
    document.getElementsByTagName("head")[0].appendChild(ioscript);

    ioscript.addEventListener ("load", ()=>{
        if(this.auto) this.connect( );
    });
  }
```

**Comment by pkaske** [comment]
chart-elements are now migrated to the latest version of lit-element and is available on npm.

Use npm install --save chart-elements. Chart.js still needs to be loaded manually as there is no esm version to my knowledge.

**Comment by rwestlund** [comment]
@pkaske Thanks, you made my day!  I think this was the last thing keeping my app on Polymer 2.  Big weekend ahead...

**Comment by pkaske** [comment]
@rwestlund cool! Let me know if any issues arise. Sorry that I was no inactive about this.
